{{- if .Values.networkPolicy.create -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "wireguard.networkPolicyName" . }}
  labels:
    {{- include "wireguard.labels" . | nindent 4 }}
  {{- with .Values.networkPolicy.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  podSelector:
    matchLabels:
      {{- include "wireguard.selectorLabels" . | nindent 6 }}
  policyTypes:
    {{- toYaml .Values.networkPolicy.policyTypes | nindent 6 }}
  {{- if hasKey .Values.networkPolicy.policies "ingress" }}
  {{- if .Values.networkPolicy.policies.ingress }}
  {{- with .Values.networkPolicy.policies.ingress }}
  ingress:
    {{- toYaml . | nindent 6 }}
  {{- end }}
  {{- else }}
  ingress: []
  {{- end }}
  {{- end }}
  {{- if hasKey .Values.networkPolicy.policies "egress" }}
  {{- if .Values.networkPolicy.policies.egress }}
  {{- with .Values.networkPolicy.policies.egress }}
  egress:
    {{- toYaml . | nindent 6 }}
  {{- end }}
  {{- else }}
  egress: []
  {{- end }}
  {{- end }}
{{- end }}